sudo: required
services:
  - docker

before_install:
  - docker build -t mertcancam/vue-test -f ./client/Dockerfile.dev ./client

script:
  - docker run mertcancam/vue-test npm run test:unit

after_success:
  - docker build -t mertcancam/risksoft-client ./client
  - docker build -t mertcancam/risksoft-nginx ./nginx
  - docker build -t mertcancam/risksoft-server ./server

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push mertcancam/risksoft-client
  - docker push mertcancam/risksoft-nginx
  - docker push mertcancam/risksoft-server

deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "risksoft"
  env: "Risksoft-env"
  bucket_name: "elasticbeanstalk-eu-central-1-445187912941"
  bucket_path: "risksoft"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"